(function() {var implementors = {};
implementors["either"] = [{text:"impl&lt;L, R&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"https://doc.rust-lang.org/nightly/core/result/enum.Result.html\" title=\"enum core::result::Result\">Result</a>&lt;R, L&gt;&gt; for <a class=\"enum\" href=\"either/enum.Either.html\" title=\"enum either::Either\">Either</a>&lt;L, R&gt;",synthetic:false,types:["either::Either"]},];
implementors["ejdb"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"bson/ordered/struct.OrderedDocument.html\" title=\"struct bson::ordered::OrderedDocument\">OrderedDocument</a>&gt; for <a class=\"struct\" href=\"ejdb/query/struct.QueryHints.html\" title=\"struct ejdb::query::QueryHints\">QueryHints</a>",synthetic:false,types:["ejdb::database::query::QueryHints"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"bson/ordered/struct.OrderedDocument.html\" title=\"struct bson::ordered::OrderedDocument\">OrderedDocument</a>&gt; for <a class=\"struct\" href=\"ejdb/query/struct.Query.html\" title=\"struct ejdb::query::Query\">Query</a>",synthetic:false,types:["ejdb::database::query::Query"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"union\" href=\"ejdb_sys/union.bson_oid_t.html\" title=\"union ejdb_sys::bson_oid_t\">bson_oid_t</a>&gt; for <a class=\"struct\" href=\"ejdb/ejdb_bson/struct.EjdbObjectId.html\" title=\"struct ejdb::ejdb_bson::EjdbObjectId\">EjdbObjectId</a>",synthetic:false,types:["ejdb::ejdb_bson::EjdbObjectId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"bson/oid/struct.ObjectId.html\" title=\"struct bson::oid::ObjectId\">ObjectId</a>&gt; for <a class=\"struct\" href=\"ejdb/ejdb_bson/struct.EjdbObjectId.html\" title=\"struct ejdb::ejdb_bson::EjdbObjectId\">EjdbObjectId</a>",synthetic:false,types:["ejdb::ejdb_bson::EjdbObjectId"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
